# Generated by Django 3.1.5 on 2021-03-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='orderd_date',
            new_name='ordered_date',
        ),
    ]
